# Generated by CONCERT
library(concert)

input_path <- "media-curation-acceptance.csv"
output_path <- "media-curation-acceptance_curated.xlsx"

tag_map <- list(chemical_name = "Name", casrn = "CASRN", result = "Result", 
    unit = "Unit", media = "Media")

reference_list_snapshot <- list(
  functional_categories = list(
    default_hash = "439259cf16a4bde4266dbd721262755d456bf581825af4f6656217c0b7c3cd9c",
    overrides = tibble::tibble(term = character(), source = character(), active = logical())
  ),
  stop_words = list(
    default_hash = "2744bec0c37b3dc837d73b6c2ccfdd21d77b1dbb065749fd9cdc2564b4fee8b7",
    overrides = tibble::tibble(
      term = c("additive", "additives", "agent", "bacteria", "base fluid", "bio", "blend", "coating", "fiber", "hazard", "inert", "inerts", "information", "ingredient", "listed", "material", "materials", "miscellaneous", "mixture", "no reportable", "not provided", "oil", "organisms", "other", "other additive", "party", "processing aid", "resin", "supplied", "surfactant", "treatment", "unavailable", "undisclosed", "various", "water treatment"),
      source = c("legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_seed", "legacy_seed", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_seed", "legacy_seed", "legacy_review", "legacy_review"),
      active = term %in% c("no reportable", "not provided", "unavailable", "undisclosed")
    )
  ),
  block_patterns = list(
    default_hash = "2e911da48110f6d28af891982d73cbd41ea6b90d24f9664757b4d6b972e7023e",
    overrides = tibble::tibble(
      term = c("acrylic polymer", "acrylic polymers", "aflatoxins", "alcohol", "alkanes", "amine soap", "aminoglycosides", "anabolic steroids", "analgesic mixtures containing phenacetin", "aristolochic acids", "barbiturates", "benzodiazepines", "beverage", "bly", "caustic salt", "cbi", "conf bus info", "confid", "confidential", "conjugated estrogens", "cyanidef", "dibenzanthracenes", "estrogen-progestogen (combined) used as menopausal therapy", "estrogens, steroidal", "etoposide in combination with cisplatin and bleomycin", "food starch", "free amines", "organic electrolyte principally involves ester carbonate", "polyester", "pp", "propriet", "proprietary", "red 4, 33", "rose", "salted fish", "secret", "sweet whey", "trade secret", "tradesecret", "undiscl", "urethane polymer", "withheld", "yeast culture"),
      source = c("legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_seed", "legacy_seed", "legacy_seed", "legacy_seed", "legacy_review", "legacy_seed", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_review", "legacy_seed", "legacy_seed", "legacy_review", "legacy_review", "legacy_review", "legacy_seed", "legacy_review", "legacy_seed", "legacy_seed", "legacy_seed", "legacy_review", "legacy_seed", "legacy_review"),
      active = term %in% c("cbi", "conf bus info", "confid", "confidential", "cyanidef", "propriet", "proprietary", "secret", "trade secret", "tradesecret", "undiscl", "withheld")
    )
  ),
  strip_terms = list(
    default_hash = "80d83122ea004ad5880ae815e974f41b0b9fb71341653ca4e5400cc9365b96d8",
    overrides = tibble::tibble(
      term = c("\\d+%$", "modified", "part [a-z]:"),
      match_mode = c("regex", "literal_word", "regex"),
      source = "legacy_review",
      active = FALSE
    )
  )
)

unit_map_snapshot <- list(
  default_hash = "eba28d26425183d35bbab7d55938b473293194324153d86bc921c3d2bfa39d47",
  overrides = tibble::tibble(
    from_unit = character(0),
    to_unit = character(0),
    multiplier = numeric(0),
    category = character(0),
    confidence = character(0),
    source = character(0),
    offset = numeric(0),
    conversion_type = character(0)
  )
)

corrections <- structure(list(pattern = character(0), replacement = character(0)), row.names = integer(0), class = c("tbl_df", 
"tbl", "data.frame"))

media_map_snapshot <- list(
  default_hash = "f9c52560e3015b9fba36198cede4e25746ef3266e38c26e146dcc1580e45f8d5",
  snapshot_version = "1",
  artifact_version = "envharmonizer-v0.1.1",
  artifact_sha256 = "56da987c0fb72e08915df5b7ecf1d099fdb03c5828fa1cc85debcceefe61daca",
  overrides = tibble::tibble(
    term = "unknown",
    canonical = "soil",
    canonical_term = "soil",
    envo_id = "ENVO:00001998",
    parent = NA_character_,
    media_category = "solid",
    source = "user",
    fetch_timestamp = NA_character_,
    assertion_mode = "user",
    confidence = "user",
    active = TRUE,
    canonical_media = NA_character_,
    term_id = "ENVO:00001998",
    parent_id = "ENVO:00010483",
    preferred_label = "soil",
    rank = "canonical",
    definition = "An environmental material which is primarily composed of minerals, varying proportions of sand, silt, and clay, organic material such as humus, interstitial gases, liquids, and a broad range of resident micro- and macroorganisms.",
    physical_phase = "solid",
    physical_state = "solid",
    is_water_based = FALSE,
    concert_unit_route = "solid",
    confidence_tier = NA_character_,
    ontology_node_id = "ENVO:00001998",
    artifact_version = "envharmonizer-v0.1.1",
    ontology_path = NA_character_
  )
)

curate_headless(
  input_path = input_path,
  output_path = output_path,
  tag_map = tag_map,
  header_row = 1L,
  wqx_threshold = 1L,
  reference_list_snapshot = reference_list_snapshot,
  postprocess_candidates = TRUE,
  harmonize = TRUE,
  format = "parquet",
  unit_map_snapshot = unit_map_snapshot,
  corrections = corrections,
  media_map_snapshot = media_map_snapshot,
  source_name = "media-curation-acceptance.csv"
)
