test_that("published media artifacts retain types, keys and deterministic bytes", {
  tables <- concert:::load_published_media_tables()
  map <- concert:::build_media_runtime_map(tables)
  expect_equal(nrow(map), 267L)
  expect_type(map$is_water_based, "logical")
  expect_type(map$active, "logical")
  expect_type(map$term_id, "character")
  expect_identical(map, concert:::build_media_runtime_map(tables))
  expect_equal(nrow(tables$matrix_terms), 1201L)
  expect_equal(nrow(tables$matrix_edges), 1425L)
  expect_gt(sum(duplicated(tables$matrix_edges$child_id)), 0L)
  old <- c("air", "aqueous", "atmospheric", "drinking water", "freshwater",
    "groundwater", "lake", "leachate", "marine", "runoff", "soil", "solid")
  # All original keys, including pending aliases, remain represented.
  dir <- concert:::resolve_media_source_dir()
  canonical <- readr::read_csv(file.path(dir, "media_canonical.csv"), show_col_types = FALSE)
  aliases <- readr::read_csv(file.path(dir, "media_aliases.csv"), show_col_types = FALSE)
  expect_true(all(unique(c(canonical$canonical_media, aliases$term)) %in% map$term))
  expect_true(all(old %in% map$term))
  expect_equal(sum(is.na(map$media_category)), 29L)
  expect_true(all(is.na(map$media_category[map$is_water_based == FALSE & map$physical_phase == "liquid"])))
})

test_that("malformed published artifacts fail integrity validation", {
  dir <- withr::local_tempdir()
  source <- file.path(concert:::resolve_media_source_dir(), "envharmonizer-0.1.1")
  dest <- file.path(dir, "envharmonizer-0.1.1")
  dir.create(dest)
  file.copy(list.files(source, full.names = TRUE), dest)
  cat("corruption", file = file.path(dest, "concert_media_map.csv"), append = TRUE)
  expect_error(concert:::load_published_media_tables(dir), "hash mismatch.*concert_media_map")
  cat("corruption", file = file.path(dest, "table-manifest.json"), append = TRUE)
  expect_error(concert:::load_published_media_tables(dir), "hash mismatch.*table-manifest")
  expect_error(concert:::verify_media_file(tempfile(), "wrong"), "hash mismatch")
})
