test_that("published identities retain context independently of routes", {
  raw <- c(" Drinking WATER ", "soil", "air", "acetone", "DMSO", "lake", "runoff", "unknown xyz", NA, "")
  result <- harmonize_media(raw)
  expect_identical(result$raw_media, raw)
  expect_equal(result$canonical_media[c(1, 6, 7)], c("drinking water", "lake water", "runoff"))
  expect_equal(result$media_category[1:5], c("aqueous", "solid", "air", NA, NA))
  expect_equal(result$routing_status[4:5], rep("unavailable", 2))
  expect_equal(result$media_flag[8:10], rep("media_unmatched", 3))
  expect_true(all(grepl("^(ENVO|FOODON|AMH):", result$term_id[1:7])))
  expect_true(all(nzchar(result$definition[1:7])))
  expect_type(result$is_water_based, "logical")
  expect_equal(result$artifact_version[1:7], rep("envharmonizer-v0.1.1", 7))
  expect_equal(nrow(harmonize_media(rep(raw, 100))), 1000L)
  expect_identical(names(harmonize_media(character())), names(result))
})

test_that("user precedence, inactive keys and conflicting fallbacks are deterministic", {
  map <- concert:::load_media_map(tempdir())
  user <- tibble::tibble(term = c("soil", "my solvent"), canonical = c("water", "acetone"),
    source = "user", active = c(FALSE, TRUE))
  # Normalize a legacy user schema before combining to avoid a stale canonical_term.
  merged <- dplyr::bind_rows(concert:::normalize_media_map_for_display(user), map)
  result <- harmonize_media(c("soil", "my solvent", "soil and water", "air / water"), media_map = merged)
  expect_equal(result$media_flag, c("media_unmatched", "", "media_unmatched", "media_unmatched"))
  expect_equal(result$canonical_media[2], "acetone")
  expect_true(is.na(result$media_category[2]))
  expect_equal(result$term_id[2], harmonize_media("acetone")$term_id)
  expect_equal(harmonize_media("freshwater sediment")$media_flag, "")
  expect_equal(harmonize_media("drinking water sample")$canonical_media, "drinking water")
  expect_error(harmonize_media("water", integer()), "equal lengths")
  expect_equal(harmonize_media("water", media_map = map[0, ])$media_flag, "media_unmatched")
})

test_that("runtime preserves originals, canonical labels and row counts on rerun", {
  raw <- tibble::tibble(media = c("Drinking WATER", "soil", "air", "acetone", "lake", "runoff", "unknown"),
    value = rep(1000, 7), unit = rep("ppb", 7))
  unit_map <- concert:::load_unit_map(concert:::resolve_reference_cache_dir())
  tags <- list(media = "Media", value = "Result", unit = "Unit")
  first <- concert:::run_harmonization_runtime(raw, tags, unit_map)
  second <- concert:::run_harmonization_runtime(first$data, tags, unit_map)
  expect_identical(second$data, first$data)
  expect_identical(second$media_results, first$media_results)
  expect_equal(first$toxval_output$media[1], "drinking water")
  expect_equal(first$toxval_output$media_original, raw$media)
  expect_equal(first$data$media_category, c("aqueous", "solid", "air", NA, "aqueous", "aqueous", NA))
  expect_equal(ncol(first$toxval_output), 56L)
  expect_equal(nrow(first$data), nrow(raw))
  expect_equal(nrow(first$toxval_output), nrow(raw))
  expect_equal(first$toxval_output$toxval_units[c(1, 2, 4, 7)], c("mg/L", "mg/kg", "ppb", "ppb"))
  only <- concert:::run_harmonization_runtime(raw["media"], list(media = "Media"), unit_map)
  expect_equal(only$toxval_output$media_original, raw$media)
  expect_equal(nrow(only$toxval_output), 7L)
})

test_that("published editor rows are inspectable before processing", {
  map <- concert:::load_media_map(tempdir())
  rows <- concert:::build_media_editor_rows(map, NULL)
  expect_equal(nrow(rows), 267L)
  expect_true(all(c("term_id", "definition", "physical_phase", "source") %in% names(rows)))
  acetone <- rows[rows$term == "acetone", ]
  expect_equal(acetone$canonical, "acetone")
  expect_true(is.na(acetone$media_category))
  expect_false(acetone$is_raw_unmatched)
})
