#' Run the full curation pipeline headlessly (without Shiny UI)
#'
#' Runs the complete CONCERT curation pipeline - file read, frontmatter
#' detection, cleaning, CompTox API search, consensus classification, and
#' 8-sheet XLSX export - from a single R script call with no Shiny session
#' required. When harmonize=TRUE, additionally runs the numeric parsing, unit
#' harmonization, and ToxVal schema mapping pipeline, and writes parquet/CSV
#' output alongside the XLSX.
#'
#' @param input_path Character. Path to the input file (CSV, XLSX, or XLS).
#' @param output_path Character. Path for the output XLSX file. Parent
#'   directories are created automatically if they do not exist. Required when
#'   `write_files = TRUE`; ignored when `write_files = FALSE`.
#' @param tag_map Named list mapping cleaned column names to tag roles. Keys
#'   must match column names *after* `janitor::clean_names()` normalization.
#'   Values are one of `"Name"`, `"CASRN"`, `"Other"`, `"Result"`, `"Numeric"`, `"Unit"`,
#'   `"Qualifier"`, `"ReportingLimit"`, `"Uncertainty"`,
#'   `"UncertaintyCoverage"`, etc. Example:
#'   `list(chemical_name = "Name", cas_number = "CASRN", result = "Result",
#'         unit = "Unit")`.
#' @param skip_flags Character vector of cleaning flag codes whose rows should
#'   skip the CompTox API search. Reserved for future use; isotope_match rows
#'   are already handled internally by `run_curation_pipeline()`.
#' @param header_row Integer or NULL. If NULL (default), frontmatter detection
#'   runs automatically. If an integer, that row number is used as the header
#'   row (manual override).
#' @param reference_lists Named list of reference data. If NULL (default), the
#'   package-bundled reference cache is loaded automatically. If provided, must
#'   contain keys: `stop_words`, `functional_categories`, `block_patterns`,
#'   `strip_terms`, `isotope_lookup`.
#' @param reference_list_snapshot Optional compact replay snapshot generated by
#'   `generate_concert_script()`. When supplied, package defaults are loaded
#'   without local `user_reference_lists.rds` overrides, verified against the
#'   snapshot hashes, and merged with snapshot overrides.
#' @param activate_all_references Logical. If TRUE, activates all cleaning
#'   reference-list rows for this run only.
#' @param verbose Logical. If TRUE (default), progress messages are printed to
#'   the console. If FALSE, all messages are suppressed.
#' @param harmonize Logical. If TRUE, runs numeric parsing, unit harmonization,
#'   and ToxVal schema mapping after curation. Default FALSE for backward compat.
#' @param format Character. Output format for ToxVal data when harmonize=TRUE.
#'   One of "parquet", "csv", or "both". Default "parquet". Ignored when
#'   harmonize=FALSE.
#' @param unit_map Tibble with unit conversion mappings, or NULL (default) to
#'   load from package cache via load_unit_map().
#' @param unit_map_snapshot Optional compact replay snapshot from
#'   `generate_concert_script()`; reconstructs the effective unit map from
#'   package defaults plus embedded deltas. Mutually exclusive with `unit_map`.
#' @param corrections Tibble with pattern/replacement columns for one-off
#'   corrections, or NULL (default) to load from package cache.
#' @param media Character. Media context for ppb/ppm routing: "aqueous", "air",
#'   or "solid". NULL (default) uses aqueous assumption.
#' @param wqx_threshold Numeric WQX fuzzy matching threshold.
#' @param starts_with Logical. If TRUE, enables CompTox starts-with fallback
#'   search for names unresolved by exact, CAS, and WQX matching.
#' @param postprocess_candidates Logical. If TRUE, runs the same enrichment,
#'   similarity scoring, and auto-resolve pass used by the Shiny app after
#'   curation. Default FALSE for backward compatibility.
#' @param review_overrides Optional function generated by
#'   `generate_concert_script()`, content-match spec from
#'   `build_review_overrides()`, or legacy positional override table/list to
#'   replay Review Results edits.
#' @param site_manifest Optional curated Dataset Context site manifest to include
#'   in the workbook export.
#' @param site_alias_map Optional Dataset Context raw-label alias map to include
#'   in the workbook export.
#' @param value_corrections Optional data frame with `column`, `pattern`,
#'   `replacement`, and optional `match_mode` columns. Applied to the detected
#'   data before cleaning. See [apply_value_corrections()].
#' @param cleaning_steps Optional named list of logicals switching cleaning
#'   steps on or off: `unicode`, `whitespace`, `cas`, `names`, `isotopes`,
#'   `multi`, `chiral`, `truncated`, `bare_formula`, `reference_flags`.
#'   Omitted names keep their defaults.
#' @param multi_analyte_resolutions Optional data frame/list with `row_index`
#'   (or `row`), `action`, and optional `value`/`values` columns. Applied after
#'   cleaning and before curation.
#' @param media_map Optional media harmonization map passed to
#'   `harmonize_media()`.
#' @param media_map_snapshot Optional compact replay snapshot from
#'   `generate_concert_script()`; reconstructs the effective media map from
#'   package defaults plus embedded deltas. Mutually exclusive with `media_map`.
#' @param write_files Logical. If TRUE (default), writes XLSX and optional
#'   parquet/CSV outputs. If FALSE, runs fully in memory and returns the same
#'   list without requiring or creating output files.
#' @param source_name Optional dataset identifier for ToxVal `source`. Defaults
#'   to the input filename stem.
#'
#' @return Invisibly returns a list:
#'   \describe{
#'     \item{When \code{harmonize=FALSE}:}{
#'       \itemize{
#'         \item \code{$data} -- resolution_state tibble
#'         \item \code{$audit_trail} -- cleaning audit tibble
#'       }
#'     }
#'     \item{When \code{harmonize=TRUE}:}{
#'       \itemize{
#'         \item \code{$data} -- 56-column ToxVal tibble (per D-05)
#'         \item \code{$audit_trail} -- cleaning audit tibble
#'         \item \code{$harmonize_audit} -- harmonization audit tibble (per D-06)
#'         \item \code{$harmonize_results} -- parsed and unit-harmonized
#'           measurement tables
#'         \item \code{$media_results}, \code{$duration_results},
#'           \code{$date_results}, and \code{$detection_results} --
#'           harmonization sidecar artifacts
#'         \item \code{$row_data} -- curated row data updated with generated
#'           detection, media, duration, and date fields
#'       }
#'     }
#'   }
#'
#' @export
#' @importFrom tools file_ext
#' @importFrom arrow write_parquet
curate_headless <- function(
  input_path,
  output_path,
  tag_map,
  skip_flags = NULL,
  header_row = NULL,
  reference_lists = NULL,
  reference_list_snapshot = NULL,
  activate_all_references = FALSE,
  verbose = TRUE,
  harmonize = FALSE,
  format = "parquet",
  unit_map = NULL,
  unit_map_snapshot = NULL,
  corrections = NULL,
  media = NULL,
  wqx_threshold = 0.85,
  starts_with = FALSE,
  postprocess_candidates = FALSE,
  review_overrides = NULL,
  site_manifest = NULL,
  site_alias_map = NULL,
  multi_analyte_resolutions = NULL,
  value_corrections = NULL,
  cleaning_steps = NULL,
  media_map = NULL,
  media_map_snapshot = NULL,
  write_files = TRUE,
  source_name = NULL
) {
  # skip_flags reserved for future use; isotope_match skip is handled internally by run_curation_pipeline()

  pipeline <- function() {
    if (write_files && (is.null(output_path) || !nzchar(output_path))) {
      stop("curate_headless: output_path is required when write_files = TRUE.")
    }
    if (!format %in% c("parquet", "csv", "both")) {
      stop(sprintf(
        "curate_headless: invalid format '%s'. Use 'parquet', 'csv', or 'both'.",
        format
      ))
    }

    state <- stage_ingest(
      input_path = input_path,
      tag_map = tag_map,
      header_row = header_row,
      reference_lists = reference_lists,
      reference_list_snapshot = reference_list_snapshot,
      activate_all_references = activate_all_references,
      site_manifest = site_manifest,
      site_alias_map = site_alias_map
    )
    state <- stage_clean(
      state,
      multi_analyte_resolutions = multi_analyte_resolutions,
      value_corrections = value_corrections,
      cleaning_steps = cleaning_steps
    )
    state <- stage_curate(
      state,
      wqx_threshold = wqx_threshold,
      starts_with = starts_with,
      postprocess_candidates = postprocess_candidates
    )
    state <- stage_review(state, review_overrides = review_overrides)
    state <- stage_harmonize(
      state,
      harmonize = harmonize,
      unit_map = unit_map,
      unit_map_snapshot = unit_map_snapshot,
      corrections = corrections,
      media_map = media_map,
      media_map_snapshot = media_map_snapshot,
      media = media,
      source_name = source_name
    )
    stage_export(state, output_path = output_path, format = format, write_files = write_files)
  }

  # Dispatch based on verbose flag
  if (verbose) {
    pipeline()
  } else {
    withCallingHandlers(
      pipeline(),
      message = function(m) invokeRestart("muffleMessage")
    )
  }
}
