# Row-level detection classification for harmonized numeric results.
#
# Detection status is numeric-only. Qualifier text is preserved as follow-up
# context, but qualifier codes and result-text qualifiers never decide detect vs
# non-detect status.

# Measurement types treated as radiological for negative-result handling.
RADIOLOGICAL_MEASUREMENT_TYPES <- c(
  "radiological_activity",
  "gross_radiological_activity",
  "aggregate_radiological_activity"
)

# Measurement types treated as chemical/non-radiological.
CHEMICAL_MEASUREMENT_TYPES <- c("chemical_concentration")

# Generated detection columns owned by CONCERT.
DETECTION_GENERATED_COLUMNS <- c(
  "lower_2sigma",
  "upper_2sigma",
  "above_reporting_limit",
  "interval_above_reporting_limit",
  "interval_crosses_reporting_limit",
  "interval_above_zero",
  "relative_uncertainty",
  "signal_to_uncertainty_ratio",
  "result_flag",
  "detected_binary",
  "reportable_detect_binary",
  "detection_event_class",
  "detection_basis",
  "detection_review_flag",
  "detection_conflict",
  "qualifier_followup_flag",
  "qualifier_followup_values",
  "numeric_followup_flag",
  "numeric_followup_reason",
  "invalid_uncertainty_flag",
  "missing_reporting_limit_flag",
  "detection_measurement_type"
)

#' Fail when source data contains CONCERT-owned detection output
#'
#' @param df Data frame to validate.
#' @param context Short context used in the error message.
#' @return Invisibly returns TRUE.
#' @keywords internal
assert_no_source_result_flag <- function(df, context = "source data") {
  if ("result_flag" %in% names(df)) {
    stop(
      sprintf(
        "%s contains 'result_flag', which is generated by CONCERT. Remove or rename the source column before processing.",
        context
      ),
      call. = FALSE
    )
  }

  invisible(TRUE)
}

#' Convert reported uncertainty to a two-sigma half-width
#'
#' Negative uncertainty values are invalid and return \code{NA_real_}; callers
#' should surface them as review context rather than allowing inverted intervals.
#' Explicit one-sigma coverage is doubled. Missing or unknown coverage is treated
#' as already two-sigma so classification remains deterministic.
#'
#' @param uncertainty_value Numeric vector of reported uncertainty.
#' @param uncertainty_coverage Character vector, e.g. "two_sigma", "one_sigma".
#' @return Numeric vector of non-negative two-sigma half-widths.
#' @export
normalize_uncertainty_to_two_sigma <- function(uncertainty_value, uncertainty_coverage = NULL) {
  unc <- suppressWarnings(as.numeric(uncertainty_value))
  unc[!is.na(unc) & unc < 0] <- NA_real_

  if (is.null(uncertainty_coverage)) {
    return(unc)
  }

  cov <- tolower(trimws(dplyr::coalesce(as.character(uncertainty_coverage), "")))
  dplyr::if_else(cov %in% c("one_sigma", "1_sigma", "1sigma", "k=1"), unc * 2, unc)
}

#' Classify row-level detection events
#'
#' Appends CONCERT-owned detection fields. \code{result_flag} is driven only by
#' numeric result, positivity, and the optional reporting limit comparison. Lab
#' qualifiers, parser qualifiers such as \code{"<"}, and narrative raw result
#' text never change \code{result_flag} or \code{detection_event_class}; any
#' non-empty qualifier value only raises follow-up/review context.
#'
#' @param df Data frame of parsed/harmonized observations.
#' @param result_col Column containing numeric result values.
#' @param reporting_limit_col Optional column containing numeric reporting
#'   limits.
#' @param uncertainty_col Optional column containing numeric uncertainty values.
#' @param qualifier_col Optional source qualifier column or columns.
#' @param parser_qualifier_col Optional parser qualifier column, e.g. from
#'   \code{parse_numeric_results()}.
#' @param raw_result_col Optional raw result text column, preserved for context.
#' @param measurement_type_col Optional measurement type column.
#' @param coverage_col Optional uncertainty coverage column.
#' @param result_unit_col Optional harmonized/original result unit column used
#'   to conservatively infer radiological rows from units such as pCi or pCi/L.
#' @param detect_operator Reporting-limit comparison for \code{result_flag}.
#'   Default \code{">"} means \code{result == reporting_limit} is non-detect.
#' @return \code{df} with generated detection fields appended.
#' @export
classify_detection_events <- function(
  df,
  result_col = "result_value",
  reporting_limit_col = "reporting_limit_value",
  uncertainty_col = "uncertainty_value",
  qualifier_col = "qualifier",
  parser_qualifier_col = "result_qualifier",
  raw_result_col = "raw_result_text",
  measurement_type_col = "measurement_type",
  coverage_col = "uncertainty_coverage",
  result_unit_col = "result_unit",
  detect_operator = c(">", ">=")
) {
  assert_no_source_result_flag(df, "classify_detection_events input")
  detect_operator <- match.arg(detect_operator)
  n <- nrow(df)

  get_col <- function(nm, default) {
    if (!is.null(nm) && length(nm) == 1L && nm %in% names(df)) {
      df[[nm]]
    } else {
      rep(default, n)
    }
  }

  result <- suppressWarnings(as.numeric(get_col(result_col, NA_real_)))
  rl <- suppressWarnings(as.numeric(get_col(reporting_limit_col, NA_real_)))
  unc_raw <- suppressWarnings(as.numeric(get_col(uncertainty_col, NA_real_)))
  coverage <- get_col(coverage_col, NA_character_)
  result_unit <- as.character(get_col(result_unit_col, NA_character_))
  mtype_source <- as.character(get_col(measurement_type_col, NA_character_))

  unit_is_rad <- is_radiological_unit(result_unit)
  mtype <- dplyr::if_else(
    !is.na(mtype_source) & nzchar(trimws(mtype_source)),
    mtype_source,
    dplyr::if_else(unit_is_rad, "radiological_activity", "chemical_concentration")
  )
  is_rad <- mtype %in% RADIOLOGICAL_MEASUREMENT_TYPES | unit_is_rad

  qualifier_cols <- c(qualifier_col, parser_qualifier_col)
  qualifier_cols <- qualifier_cols[!is.na(qualifier_cols) & nzchar(qualifier_cols)]
  qualifier_cols <- qualifier_cols[qualifier_cols %in% names(df)]
  qualifier_context <- combine_nonempty_columns(df, qualifier_cols)
  qualifier_followup_flag <- !is.na(qualifier_context) & nzchar(qualifier_context)

  invalid_uncertainty_flag <- !is.na(unc_raw) & unc_raw < 0
  unc <- normalize_uncertainty_to_two_sigma(unc_raw, coverage)
  has_unc <- !is.na(unc)

  lower_2sigma <- dplyr::if_else(!is.na(result) & has_unc, result - unc, NA_real_)
  upper_2sigma <- dplyr::if_else(!is.na(result) & has_unc, result + unc, NA_real_)

  positive_result <- !is.na(result) & result > 0
  result_na <- is.na(result)
  rl_na <- is.na(rl)
  missing_reporting_limit_flag <- rl_na

  passes_reporting_limit <- if (detect_operator == ">=") {
    !rl_na & !result_na & result >= rl
  } else {
    !rl_na & !result_na & result > rl
  }

  result_flag <- positive_result & (rl_na | passes_reporting_limit)

  interval_above_reporting_limit <- !is.na(lower_2sigma) & !rl_na & lower_2sigma >= rl
  interval_crosses_reporting_limit <- !is.na(lower_2sigma) & !is.na(upper_2sigma) &
    !rl_na & lower_2sigma < rl & upper_2sigma >= rl
  interval_above_zero <- !is.na(lower_2sigma) & lower_2sigma > 0
  relative_uncertainty <- dplyr::if_else(!is.na(result) & result != 0 & has_unc, unc / abs(result), NA_real_)
  signal_to_uncertainty_ratio <- dplyr::if_else(has_unc & unc > 0, result / (unc / 2), NA_real_)

  detection_event_class <- dplyr::case_when(
    result_na ~ "indeterminate",
    is_rad & result < 0 ~ "negative_reported_non_detect",
    !is_rad & result < 0 ~ "review_required",
    invalid_uncertainty_flag ~ "review_required",
    rl_na & positive_result ~ "review_required",
    result_flag & has_unc & interval_above_reporting_limit ~ "robust_reportable_detect",
    result_flag & has_unc ~ "estimated_reportable_detect",
    result_flag ~ "robust_reportable_detect",
    positive_result & has_unc & interval_crosses_reporting_limit ~ "threshold_ambiguous",
    positive_result & has_unc & interval_above_zero ~ "positive_below_reporting_limit",
    TRUE ~ "non_reportable"
  )

  detection_conflict <- dplyr::case_when(
    !is_rad & !result_na & result < 0 ~ "negative_non_radiological_result",
    invalid_uncertainty_flag ~ "invalid_negative_uncertainty",
    TRUE ~ NA_character_
  )

  detection_basis <- dplyr::case_when(
    result_na ~ "missing_result",
    is_rad & result < 0 ~ "negative_background_subtracted_result",
    !is_rad & result < 0 ~ "negative_non_radiological_result",
    invalid_uncertainty_flag ~ "invalid_negative_uncertainty",
    rl_na & positive_result ~ "positive_result_missing_reporting_limit",
    rl_na ~ "missing_reporting_limit",
    result_flag & has_unc & interval_above_reporting_limit ~ "positive_result_above_reporting_limit_interval_above_limit",
    result_flag & has_unc ~ "positive_result_above_reporting_limit_interval_crosses_limit",
    result_flag ~ "positive_result_above_reporting_limit",
    positive_result & has_unc & interval_crosses_reporting_limit ~ "result_below_reporting_limit_interval_overlaps_limit",
    positive_result & has_unc & interval_above_zero ~ "positive_result_below_reporting_limit",
    positive_result ~ "result_at_or_below_reporting_limit",
    TRUE ~ "non_positive_result"
  )

  coverage_chr <- tolower(trimws(dplyr::coalesce(as.character(coverage), "")))
  unknown_coverage <- is_rad & has_unc & !(coverage_chr %in%
    c("two_sigma", "2_sigma", "2sigma", "k=2", "one_sigma", "1_sigma", "1sigma", "k=1"))

  numeric_followup_reason <- combine_reason_flags(list(
    missing_result = result_na,
    positive_result_missing_reporting_limit = rl_na & positive_result,
    negative_non_radiological_result = !is_rad & !result_na & result < 0,
    invalid_negative_uncertainty = invalid_uncertainty_flag,
    radiological_result_without_uncertainty = is_rad & !result_na & result > 0 & !has_unc,
    unknown_uncertainty_coverage = unknown_coverage,
    threshold_ambiguous = detection_event_class == "threshold_ambiguous",
    positive_below_reporting_limit = detection_event_class == "positive_below_reporting_limit"
  ))
  numeric_followup_flag <- !is.na(numeric_followup_reason) & nzchar(numeric_followup_reason)

  detection_review_flag <- qualifier_followup_flag |
    numeric_followup_flag |
    detection_event_class %in% c("review_required", "threshold_ambiguous", "positive_below_reporting_limit", "indeterminate")

  df %>%
    dplyr::mutate(
      lower_2sigma = lower_2sigma,
      upper_2sigma = upper_2sigma,
      above_reporting_limit = passes_reporting_limit,
      interval_above_reporting_limit = interval_above_reporting_limit,
      interval_crosses_reporting_limit = interval_crosses_reporting_limit,
      interval_above_zero = interval_above_zero,
      relative_uncertainty = relative_uncertainty,
      signal_to_uncertainty_ratio = signal_to_uncertainty_ratio,
      result_flag = result_flag,
      detected_binary = result_flag,
      reportable_detect_binary = result_flag,
      detection_event_class = detection_event_class,
      detection_basis = detection_basis,
      detection_review_flag = detection_review_flag,
      detection_conflict = detection_conflict,
      qualifier_followup_flag = qualifier_followup_flag,
      qualifier_followup_values = qualifier_context,
      numeric_followup_flag = numeric_followup_flag,
      numeric_followup_reason = numeric_followup_reason,
      invalid_uncertainty_flag = invalid_uncertainty_flag,
      missing_reporting_limit_flag = missing_reporting_limit_flag,
      detection_measurement_type = mtype
    )
}

#' Classify harmonized tagged measurements
#'
#' Bridges \code{harmonize_tagged_numeric_measurements()} to
#' \code{classify_detection_events()} using only explicit semantic tags:
#' \code{Result}, optional \code{ReportingLimit}, optional \code{Uncertainty},
#' optional \code{UncertaintyCoverage}, and optional \code{Qualifier}.
#'
#' @param input_df Data frame used for harmonization.
#' @param tag_values Named tag map.
#' @param measurement_result Output from
#'   \code{harmonize_tagged_numeric_measurements()}.
#' @param detect_operator Reporting-limit comparison for \code{result_flag}.
#' @return List with \code{expanded_detection} aligned to primary result rows
#'   and \code{row_detection} collapsed to one row per source row.
#' @export
classify_harmonized_detection <- function(
  input_df,
  tag_values,
  measurement_result,
  detect_operator = c(">", ">=")
) {
  assert_no_source_result_flag(input_df, "harmonization input")
  detect_operator <- match.arg(detect_operator)

  if (is.list(tag_values)) {
    tag_values <- unlist(tag_values, use.names = TRUE)
  }

  if (is.null(measurement_result$primary)) {
    return(NULL)
  }

  result_cols <- names(tag_values)[tag_values == "Result"]
  if (length(result_cols) == 0) {
    return(NULL)
  }

  primary <- measurement_result$primary
  result_harmonized <- primary$harmonized
  result_parsed <- primary$parsed
  n_result <- nrow(result_harmonized)

  if (n_result == 0) {
    return(list(
      expanded_detection = tibble::tibble(),
      row_detection = empty_row_detection(nrow(input_df))
    ))
  }

  orig_row_id <- result_harmonized$orig_row_id
  result_unit <- as.character(result_harmonized$harmonized_unit)
  result_unit[is.na(result_unit) | result_unit == ""] <- as.character(result_harmonized$orig_unit)[
    is.na(result_unit) | result_unit == ""
  ]

  reporting_limit <- role_value_by_row(
    measurement_result$audit,
    role = "ReportingLimit",
    n_rows = nrow(input_df)
  )
  uncertainty <- role_value_by_row(
    measurement_result$audit,
    role = "Uncertainty",
    n_rows = nrow(input_df)
  )

  coverage_cols <- names(tag_values)[tag_values == "UncertaintyCoverage"]
  qualifier_cols <- names(tag_values)[tag_values == "Qualifier"]

  detection_input <- tibble::tibble(
    orig_row_id = orig_row_id,
    result_value = result_harmonized$harmonized_value,
    reporting_limit_value = reporting_limit$value[orig_row_id],
    uncertainty_value = uncertainty$value[orig_row_id],
    uncertainty_coverage = first_tagged_value(input_df, coverage_cols, orig_row_id),
    qualifier = combine_tagged_values(input_df, qualifier_cols, orig_row_id),
    result_qualifier = result_parsed$qualifier,
    raw_result_text = result_parsed$orig_result,
    result_unit = result_unit
  )

  expanded_detection <- classify_detection_events(
    detection_input,
    detect_operator = detect_operator
  )

  expanded_detection$numeric_followup_reason <- append_role_followup(
    expanded_detection$numeric_followup_reason,
    list(
      multiple_reporting_limit_values = reporting_limit$multiple[expanded_detection$orig_row_id],
      multiple_uncertainty_values = uncertainty$multiple[expanded_detection$orig_row_id]
    )
  )
  expanded_detection$numeric_followup_flag <- !is.na(expanded_detection$numeric_followup_reason) &
    nzchar(expanded_detection$numeric_followup_reason)
  expanded_detection$detection_review_flag <- expanded_detection$detection_review_flag |
    expanded_detection$numeric_followup_flag

  row_detection <- collapse_detection_to_rows(expanded_detection, nrow(input_df))

  list(
    expanded_detection = expanded_detection,
    row_detection = row_detection
  )
}

#' Append row-level detection fields by source row id
#'
#' @param df Data frame receiving generated detection fields.
#' @param row_detection Row-level detection output from
#'   \code{classify_harmonized_detection()}.
#' @param allow_existing_generated Logical. When TRUE, existing CONCERT-generated
#'   detection columns are replaced. Keep FALSE for source data.
#' @return \code{df} with generated detection columns appended.
#' @keywords internal
append_detection_fields <- function(df, row_detection, allow_existing_generated = FALSE) {
  if ("result_flag" %in% names(df) && !isTRUE(allow_existing_generated)) {
    assert_no_source_result_flag(df, "append_detection_fields input")
  }
  if (is.null(row_detection) || nrow(row_detection) == 0) {
    return(df)
  }

  out <- df[, setdiff(names(df), DETECTION_GENERATED_COLUMNS), drop = FALSE]
  row_match <- match(seq_len(nrow(df)), row_detection$orig_row_id)
  cols <- intersect(DETECTION_GENERATED_COLUMNS, names(row_detection))
  cols <- setdiff(cols, c("lower_2sigma", "upper_2sigma", "above_reporting_limit",
                          "interval_above_reporting_limit", "interval_crosses_reporting_limit",
                          "interval_above_zero", "relative_uncertainty",
                          "signal_to_uncertainty_ratio"))

  for (col in cols) {
    out[[col]] <- row_detection[[col]][row_match]
  }

  out
}

is_radiological_unit <- function(unit) {
  unit <- tolower(trimws(dplyr::coalesce(as.character(unit), "")))
  grepl("(^|[^a-z])(pci|ci|bq)(/|$|[^a-z])", unit, perl = TRUE)
}

combine_nonempty_columns <- function(df, cols) {
  n <- nrow(df)
  if (length(cols) == 0) {
    return(rep(NA_character_, n))
  }

  if (length(cols) == 1L) {
    value <- trimws(as.character(df[[cols[1]]]))
    value[is.na(value) | !nzchar(value)] <- NA_character_
    return(value)
  }

  result <- rep(NA_character_, n)
  for (i in seq_len(n)) {
    values <- character(0)
    for (col in cols) {
      value <- as.character(df[[col]][i])
      if (!is.na(value) && nzchar(trimws(value))) {
        values <- c(values, trimws(value))
      }
    }
    values <- unique(values)
    if (length(values) > 0) {
      result[i] <- paste(values, collapse = "; ")
    }
  }
  result
}

combine_reason_flags <- function(flags) {
  n <- if (length(flags) == 0) 0L else length(flags[[1]])
  result <- rep(NA_character_, n)
  for (i in seq_len(n)) {
    reasons <- names(flags)[vapply(flags, function(flag) isTRUE(flag[i]), logical(1))]
    if (length(reasons) > 0) {
      result[i] <- paste(reasons, collapse = "; ")
    }
  }
  result
}

append_role_followup <- function(existing, flags) {
  additions <- combine_reason_flags(flags)
  result <- existing
  needs_addition <- !is.na(additions) & nzchar(additions)
  both <- needs_addition & !is.na(result) & nzchar(result)
  result[both] <- paste(result[both], additions[both], sep = "; ")
  only_addition <- needs_addition & (is.na(result) | !nzchar(result))
  result[only_addition] <- additions[only_addition]
  result
}

role_value_by_row <- function(audit, role, n_rows) {
  value <- rep(NA_real_, n_rows)
  multiple <- rep(FALSE, n_rows)

  if (is.null(audit) || nrow(audit) == 0 || !"measurement_role" %in% names(audit)) {
    return(list(value = value, multiple = multiple))
  }

  role_rows <- audit[audit$measurement_role == role, , drop = FALSE]
  if (nrow(role_rows) == 0) {
    return(list(value = value, multiple = multiple))
  }

  row_id <- suppressWarnings(as.integer(role_rows$orig_row_id))
  vals <- suppressWarnings(as.numeric(role_rows$harmonized_value))
  keep <- !is.na(row_id) & row_id >= 1L & row_id <= n_rows & !is.na(vals)
  if (!any(keep)) {
    return(list(value = value, multiple = multiple))
  }

  grouped <- split(vals[keep], row_id[keep])
  grouped_ids <- as.integer(names(grouped))
  unique_vals <- lapply(grouped, unique)
  value[grouped_ids] <- vapply(unique_vals, `[`, numeric(1), 1L)
  multiple[grouped_ids] <- vapply(unique_vals, function(x) length(x) > 1L, logical(1))

  list(value = value, multiple = multiple)
}

first_tagged_value <- function(df, cols, row_ids) {
  values <- combine_tagged_values(df, cols, row_ids)
  values[is.na(values) | !nzchar(values)] <- NA_character_
  values
}

combine_tagged_values <- function(df, cols, row_ids) {
  if (length(cols) == 0) {
    return(rep(NA_character_, length(row_ids)))
  }

  if (length(cols) == 1L) {
    if (!cols[1] %in% names(df)) {
      return(rep(NA_character_, length(row_ids)))
    }
    result <- rep(NA_character_, length(row_ids))
    valid <- !is.na(row_ids) & row_ids >= 1L & row_ids <= nrow(df)
    value <- trimws(as.character(df[[cols[1]]][row_ids[valid]]))
    value[is.na(value) | !nzchar(value)] <- NA_character_
    result[valid] <- value
    return(result)
  }

  result <- rep(NA_character_, length(row_ids))
  for (i in seq_along(row_ids)) {
    row_id <- row_ids[i]
    values <- character(0)
    if (is.na(row_id) || row_id < 1 || row_id > nrow(df)) {
      next
    }
    for (col in cols) {
      if (!col %in% names(df)) {
        next
      }
      value <- as.character(df[[col]][row_id])
      if (!is.na(value) && nzchar(trimws(value))) {
        values <- c(values, trimws(value))
      }
    }
    values <- unique(values)
    if (length(values) > 0) {
      result[i] <- paste(values, collapse = "; ")
    }
  }
  result
}

collapse_detection_to_rows <- function(expanded_detection, n_rows) {
  row_detection <- empty_row_detection(n_rows)
  if (nrow(expanded_detection) == 0) {
    return(row_detection)
  }

  row_ids <- suppressWarnings(as.integer(expanded_detection$orig_row_id))
  valid <- !is.na(row_ids) & row_ids >= 1L & row_ids <= n_rows
  if (!any(valid)) {
    return(row_detection)
  }

  rows <- expanded_detection[valid, , drop = FALSE]
  row_ids <- row_ids[valid]
  first_idx <- !duplicated(row_ids)
  target_rows <- row_ids[first_idx]
  common_cols <- intersect(names(row_detection), names(rows))
  row_detection[target_rows, common_cols] <- rows[first_idx, common_cols, drop = FALSE]
  row_detection$orig_row_id[target_rows] <- target_rows

  any_true_cols <- c(
    "result_flag",
    "detected_binary",
    "reportable_detect_binary",
    "detection_review_flag",
    "qualifier_followup_flag",
    "numeric_followup_flag"
  )
  for (col in intersect(any_true_cols, names(rows))) {
    col_values <- rows[[col]]
    true_ids <- unique(row_ids[!is.na(col_values) & col_values])
    if (length(true_ids) > 0) {
      row_detection[[col]][true_ids] <- TRUE
    }
  }

  class_values <- rows$detection_event_class
  has_class <- !is.na(class_values)
  if (any(has_class)) {
    class_groups <- split(class_values[has_class], row_ids[has_class])
    multi_class_ids <- as.integer(names(class_groups)[
      vapply(class_groups, function(x) length(unique(x)) > 1L, logical(1))
    ])
    if (length(multi_class_ids) > 0) {
      row_detection$detection_event_class[multi_class_ids] <- "review_required"
      row_detection$detection_basis[multi_class_ids] <- "multiple_result_values"
      row_detection$numeric_followup_flag[multi_class_ids] <- TRUE
      row_detection$detection_review_flag[multi_class_ids] <- TRUE

      existing <- row_detection$numeric_followup_reason[multi_class_ids]
      needs_append <- !is.na(existing) & nzchar(existing)
      existing[needs_append] <- paste(existing[needs_append], "multiple_result_values", sep = "; ")
      existing[!needs_append] <- "multiple_result_values"
      row_detection$numeric_followup_reason[multi_class_ids] <- existing
    }
  }

  row_detection
}

empty_row_detection <- function(n_rows) {
  tibble::tibble(orig_row_id = seq_len(n_rows)) %>%
    dplyr::mutate(
      result_flag = rep(FALSE, n_rows),
      detected_binary = rep(FALSE, n_rows),
      reportable_detect_binary = rep(FALSE, n_rows),
      detection_event_class = rep(NA_character_, n_rows),
      detection_basis = rep(NA_character_, n_rows),
      detection_review_flag = rep(FALSE, n_rows),
      detection_conflict = rep(NA_character_, n_rows),
      qualifier_followup_flag = rep(FALSE, n_rows),
      qualifier_followup_values = rep(NA_character_, n_rows),
      numeric_followup_flag = rep(FALSE, n_rows),
      numeric_followup_reason = rep(NA_character_, n_rows),
      invalid_uncertainty_flag = rep(FALSE, n_rows),
      missing_reporting_limit_flag = rep(FALSE, n_rows),
      detection_measurement_type = rep(NA_character_, n_rows)
    )
}

append_reason <- function(existing, addition) {
  if (is.na(existing) || !nzchar(existing)) {
    return(addition)
  }
  paste(existing, addition, sep = "; ")
}
