name: Build Package

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build package
    uses: seanthimons/baseline/.github/workflows/build-package.yaml@733a6e4554870ab2fa8dd7495fa67bea029bb38c # v1.3.0
